### ISSUE TITLE
sötét mód csak CSS-sel

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/spruce-reporter#3]
Ha már a JS is `prefers-color-scheme`-mel megy,
akkor az a baj, hogy a Spruce nem tud csak CSS-sel váltani a két mód között?

pölö
```css
--current-color-scheme: light;
@media (prefers-color-scheme: dark) {
  --current-color-scheme: dark;
}
```
